### ISSUE TITLE
Unable to load save file - "Unsupported version 16"

### ISSUE THREAD

**Issue by squigjess** [zsennenga/hades_save_editor#28]
When loading up a save file, the program throws an exception and then crashes out.

```
Traceback (most recent call last):
  File "main.py", line 66, in open_file_name_dialog
  File "models\save_file.py", line 40, in from_file
  File "models\raw_save_file.py", line 28, in from_file
Exception: Unsupported version 16
```

I can attach my savefile if need be.

**Comment by ghost** [comment]
i have the same issue

**Comment by ShadowSkull1790** [comment]
Same here :(
