### ISSUE TITLE
Error on opening the file

### ISSUE THREAD

**Issue by adam-morel** [zsennenga/hades_save_editor#6]
Hello, i've just downloaded your program, and got an error right at the beginning. might be an "recent update" thing.
Here is the log:
Traceback (most recent call last):
  File "main.py", line 66, in open_file_name_dialog
  File "models\save_file.py", line 40, in from_file
  File "models\raw_save_file.py", line 28, in from_file
Exception: Unsupported version 15

I am on Windows 10, and used te initial release main.exe file

Edit: by downloading the sources on the main page, installing the libs and running the main.py it worked with no problems. thanks !

**Comment by zsennenga** [comment]
Should work now, give it a try
